Formatting nits
vusec/drammer pull request #2
Opened 2016-10-24 09:11 UTC by x1ddos

If you care. Feel free to ignore.

2016-10-24 14:25 UTC, bjorn3 requested changes

2016-10-24 14:25 UTC, bjorn3 commented on README.md
> +
Please keep backticks.

2016-10-24 14:25 UTC, bjorn3 commented on README.md
> +
Same here.

2016-10-24 14:28 UTC, x1ddos commented on README.md
> +
It's easier to read without the backticks in a terminal. They are not required for simple code blocks: http://markdown-guide.readthedocs.io/en/latest/basics.html#code-block.

Github adheres to the markdown syntax, too. You can preview the result of this change here: https://github.com/x1ddos/drammer/blob/9e24acac68157b42b6b8952e8df3943afe8eef2b/README.md.

2016-10-24 14:28 UTC, x1ddos commented on README.md
> +
See comment above.

2016-10-24 14:38 UTC, bjorn3 commented on README.md
> +
Didnt knew that you could do that.

2016-10-24 14:45 UTC, x1ddos commented
Rebased onto master, resolving conflicts. PTAL.

2016-10-26 14:37 UTC, m000 requested changes
Looks nice. Could you also sync the Native installation part in README.md with the changes in the Makefile?

2016-11-02 15:30 UTC, merged